# Generated by Django 5.0.6 on 2024-05-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RsevdoUser',
            new_name='PseudoUser',
        ),
    ]
