# Generated by Django 5.0.3 on 2024-03-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('top', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentToClass',
            fields=[
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.student')),
            ],
        ),
    ]
