# Generated by Django 5.0.3 on 2024-03-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_class_studenttoclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('s1', models.PositiveIntegerField()),
                ('s2', models.PositiveIntegerField()),
                ('s3', models.PositiveIntegerField()),
                ('s4', models.PositiveIntegerField()),
                ('all_year', models.PositiveIntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Days_Balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('balles', models.CharField(max_length=100)),
                ('srednii_ball', models.FloatField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.class')),
            ],
        ),
    ]
