# Generated by Django 5.0.3 on 2024-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_studenttoclass_id_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days_balls',
            name='srednii_ball',
        ),
    ]
