# Generated by Django 5.0.6 on 2024-05-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_days_balls_srednii_ball_studenttoclass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='balls',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='days_balls',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]