# Generated by Django 5.0.6 on 2024-05-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_subject_remove_balls_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balls',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='days_balls',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherByClass',
            fields=[
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.teacher')),
            ],
        ),
    ]
